name: Document
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: nightly-2026-02-20
    - uses: actions/checkout@v2
    - name: Generate documentation
      run: |
        RUSTDOCFLAGS="--cfg docsrs" \
          cargo doc --no-deps --all-features \
          -p futures-core \
          -p julep-iced-beacon \
          -p julep-iced-core \
          -p julep-iced-debug \
          -p julep-iced-devtools \
          -p julep-iced-futures \
          -p julep-iced-graphics \
          -p julep-iced-highlighter \
          -p julep-iced-renderer \
          -p julep-iced-runtime \
          -p julep-iced-tiny-skia \
          -p julep-iced-wgpu \
          -p julep-iced-widget \
          -p julep-iced-winit \
          -p julep-iced-test \
          -p julep-iced
    - name: Copy redirect file as index.html
      run: cp docs/redirect.html target/doc/index.html
    - name: Publish documentation
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
        publish_dir: ./target/doc
